version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "test"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5
    groups:
      python:
        patterns: ["*"]

  - package-ecosystem: "docker"
    directory: "/"
    target-branch: "test"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    target-branch: "test"
    schedule:
      interval: "weekly"
